
# Assign the design verilog ports to the device IO pins
set_property PACKAGE_PIN U18 [get_ports reset]
set_property PACKAGE_PIN U14 [get_ports {IOs[0]}]
set_property PACKAGE_PIN W16 [get_ports {IOs[1]}]
set_property PACKAGE_PIN U16 [get_ports {IOs[5]}]
set_property PACKAGE_PIN V17 [get_ports {IOs[7]}]
set_property PACKAGE_PIN W18 [get_ports {IOs[9]}]
set_property PACKAGE_PIN W15 [get_ports {IOs[2]}]
set_property PACKAGE_PIN V14 [get_ports {IOs[4]}]
set_property PACKAGE_PIN U15 [get_ports {IOs[6]}]
set_property PACKAGE_PIN U17 [get_ports beep]
set_property PACKAGE_PIN W14 [get_ports {IOs[3]}]
set_property PACKAGE_PIN V16 [get_ports {IOs[8]}]
set_property PACKAGE_PIN N17 [get_ports clk_in]

# set some IO property of the ports
set_property DIRECTION IN [get_ports {IOs[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IOs[0]}]
set_property DIRECTION IN [get_ports {IOs[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IOs[1]}]
set_property DIRECTION IN [get_ports {IOs[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IOs[2]}]
set_property DIRECTION IN [get_ports {IOs[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IOs[3]}]
set_property DIRECTION IN [get_ports {IOs[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IOs[4]}]
set_property DIRECTION IN [get_ports {IOs[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IOs[5]}]
set_property DIRECTION IN [get_ports {IOs[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IOs[6]}]
set_property DIRECTION IN [get_ports {IOs[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IOs[7]}]
set_property DIRECTION IN [get_ports {IOs[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IOs[8]}]
set_property DIRECTION IN [get_ports {IOs[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IOs[9]}]
set_property DIRECTION IN [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property DIRECTION IN [get_ports clk_in]
set_property IOSTANDARD LVCMOS18 [get_ports clk_in]
set_property DIRECTION OUT [get_ports beep]
set_property IOSTANDARD LVCMOS18 [get_ports beep]
set_property DRIVE 12 [get_ports beep]
set_property SLEW SLOW [get_ports beep]

# define the property of a clock port so Vivado know this port is for a CLOCK signal
# and it can do something properly for this port
create_clock -period 2.000  -waveform {0.000 5.000} [get_ports clk_in]